// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: soc_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestionCoreService_FetchAlertContext_FullMethodName            = "/pb.IngestionCoreService/FetchAlertContext"
	IngestionCoreService_PushBlockDirective_FullMethodName          = "/pb.IngestionCoreService/PushBlockDirective"
	IngestionCoreService_SubscribeToQualifiedEvents_FullMethodName  = "/pb.IngestionCoreService/SubscribeToQualifiedEvents"
)

// IngestionCoreServiceClient is the client API for IngestionCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==============================================================================
// 1. 🌐 COMPONENT PLACEMENT & GLOBAL WORKFLOW TRACE
//    - gRPC Contract Layer: Acts as the primary interconnect between the Go
//      Ingestion core and the downstream Python ML Inference orchestration layer.
//    - Upstream: Go Core (Port 9090 Server) | Downstream: Python LangGraph Agent (Client)
// 2. 🛡️ LOGICAL INTENT & SYSTEM RESPONSIBILITY
//    - Defines the strict, statically-typed client API interface for dispatching
//      containment commands and streaming SIEM alert context.
//    - Relies on protoc-gen-go-grpc generated stubs to avoid manual socket programming.
// 3. 🚨 INFRASTRUCTURE GUARDRAILS & RESOURCE CONSTRAINTS
//    - Go Ingestion: gRPC streams (`ServerStreamingClient`) hold persistent HTTP/2
//      TCP connections open. Ensure client `.CloseSend()` is called to prevent
//      file-descriptor (FD) leaks.
//    - Protobuf / SQL Schema: This is a strongly typed contract. Modifying this
//      interface requires rebuilding both Go and Python generated definitions.
// 4. 🔗 CROSS-MODULE INTERFACE & CONTRACT BOUNDARIES
//    - Cross-module boundary over TCP 0.0.0.0:9090.
//    - Schema Definition: `shared-proto/soc_service.proto`.
// 5. ☣️ FAILURE DOMAINS & RESILIENCE STATE
//    - Failure Mode: If the gRPC server is unreachable, `cc.NewStream` or `cc.Invoke`
//      will timeout/error, causing the Python ML layer to fail executing directives.
//    - Fallback State: Fail-Closed on directive execution (cannot block IPs without connection).
// ==============================================================================
// The Ingestion Core Service manages type-safe data pipelines between Go and Python Agent layers.
type IngestionCoreServiceClient interface {
	// FETCH LOG CONTEXT: Uses Server-to-Client Streaming to handle massive logs without RAM bloat
	FetchAlertContext(ctx context.Context, in *LogContextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogContextResponse], error)
	// CONTAINMENT CALLS: Asynchronous, audited, and strictly validated
	PushBlockDirective(ctx context.Context, in *BlockDirectiveRequest, opts ...grpc.CallOption) (*BlockDirectiveResponse, error)
	// LIVE TRIAGE SUBSCRIPTION: Python AI backend subscribes to qualified events from Go ingestion edge
	SubscribeToQualifiedEvents(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QualifiedEvent], error)
}

type ingestionCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestionCoreServiceClient(cc grpc.ClientConnInterface) IngestionCoreServiceClient {
	return &ingestionCoreServiceClient{cc}
}

func (c *ingestionCoreServiceClient) FetchAlertContext(ctx context.Context, in *LogContextRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogContextResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionCoreService_ServiceDesc.Streams[0], IngestionCoreService_FetchAlertContext_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogContextRequest, LogContextResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionCoreService_FetchAlertContextClient = grpc.ServerStreamingClient[LogContextResponse]

func (c *ingestionCoreServiceClient) PushBlockDirective(ctx context.Context, in *BlockDirectiveRequest, opts ...grpc.CallOption) (*BlockDirectiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockDirectiveResponse)
	err := c.cc.Invoke(ctx, IngestionCoreService_PushBlockDirective_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestionCoreServiceClient) SubscribeToQualifiedEvents(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QualifiedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestionCoreService_ServiceDesc.Streams[1], IngestionCoreService_SubscribeToQualifiedEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, QualifiedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility.
type IngestionCoreService_SubscribeToQualifiedEventsClient = grpc.ServerStreamingClient[QualifiedEvent]

// IngestionCoreServiceServer is the server API for IngestionCoreService service.
// All implementations must embed UnimplementedIngestionCoreServiceServer
// for forward compatibility.
//
// ==============================================================================
// 1. 🌐 COMPONENT PLACEMENT & GLOBAL WORKFLOW TRACE
//    - gRPC Request Handler: Embedded directly into the Go Main event loop (`main.go`).
//    - Upstream: Python ML Inference (Caller) | Downstream: Go internal execution logic
// 2. 🛡️ LOGICAL INTENT & SYSTEM RESPONSIBILITY
//    - Provides the base interface that `grpcServer` struct must implement to
//      expose `FetchAlertContext` and `PushBlockDirective` via RPC.
// 3. 🚨 INFRASTRUCTURE GUARDRAILS & RESOURCE CONSTRAINTS
//    - Go Ingestion: Server handlers spin up dedicated goroutines per RPC invocation.
//      Unbounded requests from compromised agents can exhaust goroutine limits.
// 4. 🔗 CROSS-MODULE INTERFACE & CONTRACT BOUNDARIES
//    - Inter-service listener bound to TCP:9090.
//    - Schema Definition: `shared-proto/soc_service.proto`.
// 5. ☣️ FAILURE DOMAINS & RESILIENCE STATE
//    - Failure Mode: `UnimplementedIngestionCoreServiceServer` will return
//      `codes.Unimplemented` if a method is missing in the Go implementation.
//    - Fallback State: Graceful error returned to the Python client. No panic.
// ==============================================================================
// The Ingestion Core Service manages type-safe data pipelines between Go and Python Agent layers.
type IngestionCoreServiceServer interface {
	// FETCH LOG CONTEXT: Uses Server-to-Client Streaming to handle massive logs without RAM bloat
	FetchAlertContext(*LogContextRequest, grpc.ServerStreamingServer[LogContextResponse]) error
	// CONTAINMENT CALLS: Asynchronous, audited, and strictly validated
	PushBlockDirective(context.Context, *BlockDirectiveRequest) (*BlockDirectiveResponse, error)
	// LIVE TRIAGE SUBSCRIPTION: Python AI backend subscribes to qualified events
	SubscribeToQualifiedEvents(*SubscriptionRequest, grpc.ServerStreamingServer[QualifiedEvent]) error
	mustEmbedUnimplementedIngestionCoreServiceServer()
}

// UnimplementedIngestionCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestionCoreServiceServer struct{}

func (UnimplementedIngestionCoreServiceServer) FetchAlertContext(*LogContextRequest, grpc.ServerStreamingServer[LogContextResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchAlertContext not implemented")
}
func (UnimplementedIngestionCoreServiceServer) PushBlockDirective(context.Context, *BlockDirectiveRequest) (*BlockDirectiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushBlockDirective not implemented")
}
func (UnimplementedIngestionCoreServiceServer) SubscribeToQualifiedEvents(*SubscriptionRequest, grpc.ServerStreamingServer[QualifiedEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToQualifiedEvents not implemented")
}
func (UnimplementedIngestionCoreServiceServer) mustEmbedUnimplementedIngestionCoreServiceServer() {}
func (UnimplementedIngestionCoreServiceServer) testEmbeddedByValue()                              {}

// UnsafeIngestionCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestionCoreServiceServer will
// result in compilation errors.
type UnsafeIngestionCoreServiceServer interface {
	mustEmbedUnimplementedIngestionCoreServiceServer()
}

func RegisterIngestionCoreServiceServer(s grpc.ServiceRegistrar, srv IngestionCoreServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestionCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestionCoreService_ServiceDesc, srv)
}

func _IngestionCoreService_FetchAlertContext_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogContextRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IngestionCoreServiceServer).FetchAlertContext(m, &grpc.GenericServerStream[LogContextRequest, LogContextResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestionCoreService_FetchAlertContextServer = grpc.ServerStreamingServer[LogContextResponse]

func _IngestionCoreService_PushBlockDirective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockDirectiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestionCoreServiceServer).PushBlockDirective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestionCoreService_PushBlockDirective_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestionCoreServiceServer).PushBlockDirective(ctx, req.(*BlockDirectiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestionCoreService_SubscribeToQualifiedEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IngestionCoreServiceServer).SubscribeToQualifiedEvents(m, &grpc.GenericServerStream[SubscriptionRequest, QualifiedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility.
type IngestionCoreService_SubscribeToQualifiedEventsServer = grpc.ServerStreamingServer[QualifiedEvent]

// IngestionCoreService_ServiceDesc is the grpc.ServiceDesc for IngestionCoreService service.
var IngestionCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IngestionCoreService",
	HandlerType: (*IngestionCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBlockDirective",
			Handler:    _IngestionCoreService_PushBlockDirective_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchAlertContext",
			Handler:       _IngestionCoreService_FetchAlertContext_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToQualifiedEvents",
			Handler:       _IngestionCoreService_SubscribeToQualifiedEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "soc_service.proto",
}
