// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: soc_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ───────────────────────────────────────────────────────────────
// DATA MODEL CORRECTIONS FOR HIGH-THROUGHPUT SIEM SCANS
// ───────────────────────────────────────────────────────────────
// ==============================================================================
// 1. 🌐 COMPONENT PLACEMENT & GLOBAL WORKFLOW TRACE
//    - Payload Structure: Instantiated by the Python ML Agent to request
//      deep context on specific SIEM alerts from the Go backend.
//    - Upstream: Python LangGraph Agent | Downstream: Go IngestionCoreServiceServer
// 2. 🛡️ LOGICAL INTENT & SYSTEM RESPONSIBILITY
//    - Encapsulates the request payload to pull structured evidence streams.
//    - Architected to enforce a `max_records_limit` to prevent catastrophic
//      data pulls from corrupt ML logic.
// 3. 🚨 INFRASTRUCTURE GUARDRAILS & RESOURCE CONSTRAINTS
//    - Protobuf / SQL Schema: Adding new required fields will break backwards
//      compatibility. Always append new fields as optional (proto3 default).
// 4. 🔗 CROSS-MODULE INTERFACE & CONTRACT BOUNDARIES
//    - Sent across gRPC HTTP/2 tunnels via `FetchAlertContext` RPC.
// 5. ☣️ FAILURE DOMAINS & RESILIENCE STATE
//    - Failure Mode: Malformed bytes will cause Protobuf unmarshal errors at
//      the network edge, instantly dropping the request.
//    - Fallback State: Drop-and-Log un-parseable payloads.
// ==============================================================================
type LogContextRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EvidenceIds     []string               `protobuf:"bytes,1,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	MaxRecordsLimit int32                  `protobuf:"varint,2,opt,name=max_records_limit,json=maxRecordsLimit,proto3" json:"max_records_limit,omitempty"` // Prevent agents from accidentally requesting a 10GB trace
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogContextRequest) Reset() {
	*x = LogContextRequest{}
	mi := &file_soc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogContextRequest) ProtoMessage() {}

func (x *LogContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogContextRequest.ProtoReflect.Descriptor instead.
func (*LogContextRequest) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogContextRequest) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

func (x *LogContextRequest) GetMaxRecordsLimit() int32 {
	if x != nil {
		return x.MaxRecordsLimit
	}
	return 0
}

// Structuring individual logs natively eliminates heavy JSON parsing latencies
type SecurityEventDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceIp       string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	PrincipalUser  string                 `protobuf:"bytes,4,opt,name=principal_user,json=principalUser,proto3" json:"principal_user,omitempty"`
	ActionExecuted string                 `protobuf:"bytes,5,opt,name=action_executed,json=actionExecuted,proto3" json:"action_executed,omitempty"`
	RiskScore      uint32                 `protobuf:"varint,6,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SecurityEventDetail) Reset() {
	*x = SecurityEventDetail{}
	mi := &file_soc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEventDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEventDetail) ProtoMessage() {}

func (x *SecurityEventDetail) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEventDetail.ProtoReflect.Descriptor instead.
func (*SecurityEventDetail) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityEventDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SecurityEventDetail) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SecurityEventDetail) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *SecurityEventDetail) GetPrincipalUser() string {
	if x != nil {
		return x.PrincipalUser
	}
	return ""
}

func (x *SecurityEventDetail) GetActionExecuted() string {
	if x != nil {
		return x.ActionExecuted
	}
	return ""
}

func (x *SecurityEventDetail) GetRiskScore() uint32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

type LogContextResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentBatchIndex int32                  `protobuf:"varint,2,opt,name=current_batch_index,json=currentBatchIndex,proto3" json:"current_batch_index,omitempty"`
	// FIXED: Embedding native messages completely eliminates JSON string conversion overhead
	Events        []*SecurityEventDetail `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogContextResponse) Reset() {
	*x = LogContextResponse{}
	mi := &file_soc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogContextResponse) ProtoMessage() {}

func (x *LogContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogContextResponse.ProtoReflect.Descriptor instead.
func (*LogContextResponse) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogContextResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogContextResponse) GetCurrentBatchIndex() int32 {
	if x != nil {
		return x.CurrentBatchIndex
	}
	return 0
}

func (x *LogContextResponse) GetEvents() []*SecurityEventDetail {
	if x != nil {
		return x.Events
	}
	return nil
}

// ───────────────────────────────────────────────────────────────
// DATA MODEL CORRECTIONS FOR AUDITING & POLICY COMPLIANCE
// ───────────────────────────────────────────────────────────────
// ==============================================================================
// 1. 🌐 COMPONENT PLACEMENT & GLOBAL WORKFLOW TRACE
//    - Command Execution Payload: Triggered by the Python Agent to enact
//      real-world firewall modifications.
//    - Upstream: Python AI ML Orchestrator | Downstream: Go Ingestion Firewall API
// 2. 🛡️ LOGICAL INTENT & SYSTEM RESPONSIBILITY
//    - Transmits explicit IP containment instructions with heavy audit metadata
//      (ActorId, SessionId, JWT). Designed specifically for zero-trust architectures.
// 3. 🚨 INFRASTRUCTURE GUARDRAILS & RESOURCE CONSTRAINTS
//    - Protobuf / SQL Schema: Heavily relies on `authorization_jwt` for RBAC.
//      If this field is empty, the Go layer will forcefully reject the transaction.
// 4. 🔗 CROSS-MODULE INTERFACE & CONTRACT BOUNDARIES
//    - Payload definition for the `PushBlockDirective` RPC call.
// 5. ☣️ FAILURE DOMAINS & RESILIENCE STATE
//    - Failure Mode: Missing `ip_address` or `authorization_jwt` will cause
//      validation failure inside `PushBlockDirective` handler.
//    - Fallback State: Fail-Closed. Command aborted.
// ==============================================================================
type BlockDirectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Justification string                 `protobuf:"bytes,2,opt,name=justification,proto3" json:"justification,omitempty"`
	// FIXED: Mandatory Audit Context Fields for FR7 Enforcement
	ActorId          string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`                            // Track precisely which Agent (e.g., 'ResponseAgent') triggered the command
	SessionId        string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                      // Tie the block directly back to the active LangGraph investigation ID
	AuthorizationJwt string `protobuf:"bytes,5,opt,name=authorization_jwt,json=authorizationJwt,proto3" json:"authorization_jwt,omitempty"` // User authentication token used to verify RBAC down at the Go layer
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockDirectiveRequest) Reset() {
	*x = BlockDirectiveRequest{}
	mi := &file_soc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDirectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDirectiveRequest) ProtoMessage() {}

func (x *BlockDirectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDirectiveRequest.ProtoReflect.Descriptor instead.
func (*BlockDirectiveRequest) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{3}
}

func (x *BlockDirectiveRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *BlockDirectiveRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *BlockDirectiveRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *BlockDirectiveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BlockDirectiveRequest) GetAuthorizationJwt() string {
	if x != nil {
		return x.AuthorizationJwt
	}
	return ""
}

type BlockDirectiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LogId         string                 `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDirectiveResponse) Reset() {
	*x = BlockDirectiveResponse{}
	mi := &file_soc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDirectiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDirectiveResponse) ProtoMessage() {}

func (x *BlockDirectiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDirectiveResponse.ProtoReflect.Descriptor instead.
func (*BlockDirectiveResponse) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{4}
}

func (x *BlockDirectiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockDirectiveResponse) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *BlockDirectiveResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
}

func (x *SubscriptionRequest) String() string {
	return x.SubscriberId
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		return ms
	}
	return nil
}

func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type QualifiedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EndpointId     string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	EndpointType   string                 `protobuf:"bytes,4,opt,name=endpoint_type,json=endpointType,proto3" json:"endpoint_type,omitempty"`
	RiskScore      uint32                 `protobuf:"varint,5,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	IngestedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`
	RawPayloadJson string                 `protobuf:"bytes,7,opt,name=raw_payload_json,json=rawPayloadJson,proto3" json:"raw_payload_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QualifiedEvent) Reset() {
	*x = QualifiedEvent{}
}

func (x *QualifiedEvent) String() string {
	return x.CorrelationId
}

func (*QualifiedEvent) ProtoMessage() {}

func (x *QualifiedEvent) ProtoReflect() protoreflect.Message {
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		return ms
	}
	return nil
}


func (*QualifiedEvent) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{6}
}

func (x *QualifiedEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QualifiedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QualifiedEvent) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *QualifiedEvent) GetEndpointType() string {
	if x != nil {
		return x.EndpointType
	}
	return ""
}

func (x *QualifiedEvent) GetRiskScore() uint32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *QualifiedEvent) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

func (x *QualifiedEvent) GetRawPayloadJson() string {
	if x != nil {
		return x.RawPayloadJson
	}
	return ""
}

var File_soc_service_proto protoreflect.FileDescriptor

const file_soc_service_proto_rawDesc = "" +
	"\n" +
	"\x11soc_service.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x11LogContextRequest\x12!\n" +
	"\fevidence_ids\x18\x01 \x03(\tR\vevidenceIds\x12*\n" +
	"\x11max_records_limit\x18\x02 \x01(\x05R\x0fmaxRecordsLimit\"\xf6\x01\n" +
	"\x13SecurityEventDetail\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12%\n" +
	"\x0eprincipal_user\x18\x04 \x01(\tR\rprincipalUser\x12'\n" +
	"\x0faction_executed\x18\x05 \x01(\tR\x0eactionExecuted\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x06 \x01(\rR\triskScore\"\x8d\x01\n" +
	"\x12LogContextResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12.\n" +
	"\x13current_batch_index\x18\x02 \x01(\x05R\x11currentBatchIndex\x12/\n" +
	"\x06events\x18\x03 \x03(\v2\x17.pb.SecurityEventDetailR\x06events\"\xc3\x01\n" +
	"\x15BlockDirectiveRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12$\n" +
	"\rjustification\x18\x02 \x01(\tR\rjustification\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12+\n" +
	"\x11authorization_jwt\x18\x05 \x01(\tR\x10authorizationJwt\"\x86\x01\n" +
	"\x16BlockDirectiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\tR\x05logId\x12;\n" +
	"\vexecuted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt2\xa9\x01\n" +
	"\x14IngestionCoreService\x12D\n" +
	"\x11FetchAlertContext\x12\x15.pb.LogContextRequest\x1a\x16.pb.LogContextResponse0\x01\x12K\n" +
	"\x12PushBlockDirective\x12\x19.pb.BlockDirectiveRequest\x1a\x1a.pb.BlockDirectiveResponseB\x10Z\x0ecore-ingest/pbb\x06proto3"

var (
	file_soc_service_proto_rawDescOnce sync.Once
	file_soc_service_proto_rawDescData []byte
)

func file_soc_service_proto_rawDescGZIP() []byte {
	file_soc_service_proto_rawDescOnce.Do(func() {
		file_soc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_soc_service_proto_rawDesc), len(file_soc_service_proto_rawDesc)))
	})
	return file_soc_service_proto_rawDescData
}

var file_soc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_soc_service_proto_goTypes = []any{
	(*LogContextRequest)(nil),      // 0: pb.LogContextRequest
	(*SecurityEventDetail)(nil),    // 1: pb.SecurityEventDetail
	(*LogContextResponse)(nil),     // 2: pb.LogContextResponse
	(*BlockDirectiveRequest)(nil),  // 3: pb.BlockDirectiveRequest
	(*BlockDirectiveResponse)(nil), // 4: pb.BlockDirectiveResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_soc_service_proto_depIdxs = []int32{
	5, // 0: pb.SecurityEventDetail.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: pb.LogContextResponse.events:type_name -> pb.SecurityEventDetail
	5, // 2: pb.BlockDirectiveResponse.executed_at:type_name -> google.protobuf.Timestamp
	0, // 3: pb.IngestionCoreService.FetchAlertContext:input_type -> pb.LogContextRequest
	3, // 4: pb.IngestionCoreService.PushBlockDirective:input_type -> pb.BlockDirectiveRequest
	2, // 5: pb.IngestionCoreService.FetchAlertContext:output_type -> pb.LogContextResponse
	4, // 6: pb.IngestionCoreService.PushBlockDirective:output_type -> pb.BlockDirectiveResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_soc_service_proto_init() }
func file_soc_service_proto_init() {
	if File_soc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_soc_service_proto_rawDesc), len(file_soc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soc_service_proto_goTypes,
		DependencyIndexes: file_soc_service_proto_depIdxs,
		MessageInfos:      file_soc_service_proto_msgTypes,
	}.Build()
	File_soc_service_proto = out.File
	file_soc_service_proto_goTypes = nil
	file_soc_service_proto_depIdxs = nil
}


