// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: soc_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ───────────────────────────────────────────────────────────────
// DATA MODEL CORRECTIONS FOR HIGH-THROUGHPUT SIEM SCANS
// ───────────────────────────────────────────────────────────────
type LogContextRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EvidenceIds     []string               `protobuf:"bytes,1,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	MaxRecordsLimit int32                  `protobuf:"varint,2,opt,name=max_records_limit,json=maxRecordsLimit,proto3" json:"max_records_limit,omitempty"` // Prevent agents from accidentally requesting a 10GB trace
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogContextRequest) Reset() {
	*x = LogContextRequest{}
	mi := &file_soc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogContextRequest) ProtoMessage() {}

func (x *LogContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogContextRequest.ProtoReflect.Descriptor instead.
func (*LogContextRequest) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogContextRequest) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

func (x *LogContextRequest) GetMaxRecordsLimit() int32 {
	if x != nil {
		return x.MaxRecordsLimit
	}
	return 0
}

// Structuring individual logs natively eliminates heavy JSON parsing latencies
type SecurityEventDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceIp        string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	PrincipalUser   string                 `protobuf:"bytes,4,opt,name=principal_user,json=principalUser,proto3" json:"principal_user,omitempty"`
	ActionExecuted  string                 `protobuf:"bytes,5,opt,name=action_executed,json=actionExecuted,proto3" json:"action_executed,omitempty"`
	RiskScore       uint32                 `protobuf:"varint,6,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	DestinationIp   string                 `protobuf:"bytes,7,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort int32                  `protobuf:"varint,8,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,9,opt,name=protocol,proto3" json:"protocol,omitempty"`
	DnsDomain       string                 `protobuf:"bytes,10,opt,name=dns_domain,json=dnsDomain,proto3" json:"dns_domain,omitempty"`
	FlowId          string                 `protobuf:"bytes,11,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	BytesOut        uint64                 `protobuf:"varint,12,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	BytesIn         uint64                 `protobuf:"varint,13,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	PacketsOut      uint32                 `protobuf:"varint,14,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	PacketsIn       uint32                 `protobuf:"varint,15,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	FlowDuration    float64                `protobuf:"fixed64,16,opt,name=flow_duration,json=flowDuration,proto3" json:"flow_duration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecurityEventDetail) Reset() {
	*x = SecurityEventDetail{}
	mi := &file_soc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEventDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEventDetail) ProtoMessage() {}

func (x *SecurityEventDetail) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEventDetail.ProtoReflect.Descriptor instead.
func (*SecurityEventDetail) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityEventDetail) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SecurityEventDetail) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SecurityEventDetail) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *SecurityEventDetail) GetPrincipalUser() string {
	if x != nil {
		return x.PrincipalUser
	}
	return ""
}

func (x *SecurityEventDetail) GetActionExecuted() string {
	if x != nil {
		return x.ActionExecuted
	}
	return ""
}

func (x *SecurityEventDetail) GetRiskScore() uint32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *SecurityEventDetail) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *SecurityEventDetail) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *SecurityEventDetail) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *SecurityEventDetail) GetDnsDomain() string {
	if x != nil {
		return x.DnsDomain
	}
	return ""
}

func (x *SecurityEventDetail) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *SecurityEventDetail) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *SecurityEventDetail) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *SecurityEventDetail) GetPacketsOut() uint32 {
	if x != nil {
		return x.PacketsOut
	}
	return 0
}

func (x *SecurityEventDetail) GetPacketsIn() uint32 {
	if x != nil {
		return x.PacketsIn
	}
	return 0
}

func (x *SecurityEventDetail) GetFlowDuration() float64 {
	if x != nil {
		return x.FlowDuration
	}
	return 0
}

type LogContextResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentBatchIndex int32                  `protobuf:"varint,2,opt,name=current_batch_index,json=currentBatchIndex,proto3" json:"current_batch_index,omitempty"`
	// FIXED: Embedding native messages completely eliminates JSON string conversion overhead
	Events        []*SecurityEventDetail `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogContextResponse) Reset() {
	*x = LogContextResponse{}
	mi := &file_soc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogContextResponse) ProtoMessage() {}

func (x *LogContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogContextResponse.ProtoReflect.Descriptor instead.
func (*LogContextResponse) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogContextResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogContextResponse) GetCurrentBatchIndex() int32 {
	if x != nil {
		return x.CurrentBatchIndex
	}
	return 0
}

func (x *LogContextResponse) GetEvents() []*SecurityEventDetail {
	if x != nil {
		return x.Events
	}
	return nil
}

// ───────────────────────────────────────────────────────────────
// DATA MODEL CORRECTIONS FOR AUDITING & POLICY COMPLIANCE
// ───────────────────────────────────────────────────────────────
type BlockDirectiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Justification string                 `protobuf:"bytes,2,opt,name=justification,proto3" json:"justification,omitempty"`
	// FIXED: Mandatory Audit Context Fields for FR7 Enforcement
	ActorId          string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`                            // Track precisely which Agent (e.g., 'ResponseAgent') triggered the command
	SessionId        string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                      // Tie the block directly back to the active LangGraph investigation ID
	AuthorizationJwt string `protobuf:"bytes,5,opt,name=authorization_jwt,json=authorizationJwt,proto3" json:"authorization_jwt,omitempty"` // User authentication token used to verify RBAC down at the Go layer
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BlockDirectiveRequest) Reset() {
	*x = BlockDirectiveRequest{}
	mi := &file_soc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDirectiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDirectiveRequest) ProtoMessage() {}

func (x *BlockDirectiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDirectiveRequest.ProtoReflect.Descriptor instead.
func (*BlockDirectiveRequest) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{3}
}

func (x *BlockDirectiveRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *BlockDirectiveRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *BlockDirectiveRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *BlockDirectiveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BlockDirectiveRequest) GetAuthorizationJwt() string {
	if x != nil {
		return x.AuthorizationJwt
	}
	return ""
}

type BlockDirectiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LogId         string                 `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockDirectiveResponse) Reset() {
	*x = BlockDirectiveResponse{}
	mi := &file_soc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockDirectiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDirectiveResponse) ProtoMessage() {}

func (x *BlockDirectiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDirectiveResponse.ProtoReflect.Descriptor instead.
func (*BlockDirectiveResponse) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{4}
}

func (x *BlockDirectiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockDirectiveResponse) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *BlockDirectiveResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

// SubscriptionRequest is sent once by the Python consumer to open the stream.
// subscriber_id identifies the Python backend instance (useful in multi-replica setups).
type SubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_soc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

// QualifiedEvent is a CDM-parsed, correlation-tagged telemetry event that is
// ready for LangGraph AI triage. Carries the end-to-end correlationId generated
// at the Go ingestion edge so all downstream LangGraph node events share the same ID.
type QualifiedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId   string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`      // End-to-end trace ID (set at HTTP edge in core-ingest)
	EventType       string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                  // e.g., "Brute_Force", "Ransomware_Behavior"
	EndpointId      string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`               // Originating spoke identity
	EndpointType    string                 `protobuf:"bytes,4,opt,name=endpoint_type,json=endpointType,proto3" json:"endpoint_type,omitempty"`         // paas | iaas | local_cf_tunnel
	SourceIp        string                 `protobuf:"bytes,5,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                     // True client IP (post CF-Connecting-IP extraction)
	RiskScore       uint32                 `protobuf:"varint,6,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`                 // Pre-computed edge risk score (0-100)
	IngestedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"`               // Timestamp the event was accepted at the Go edge
	RawPayloadJson  string                 `protobuf:"bytes,8,opt,name=raw_payload_json,json=rawPayloadJson,proto3" json:"raw_payload_json,omitempty"` // Serialized CDM graph for advanced ML inference
	ProvenanceGraph string                 `protobuf:"bytes,9,opt,name=provenance_graph,json=provenanceGraph,proto3" json:"provenance_graph,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QualifiedEvent) Reset() {
	*x = QualifiedEvent{}
	mi := &file_soc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualifiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualifiedEvent) ProtoMessage() {}

func (x *QualifiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_soc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualifiedEvent.ProtoReflect.Descriptor instead.
func (*QualifiedEvent) Descriptor() ([]byte, []int) {
	return file_soc_service_proto_rawDescGZIP(), []int{6}
}

func (x *QualifiedEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *QualifiedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QualifiedEvent) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *QualifiedEvent) GetEndpointType() string {
	if x != nil {
		return x.EndpointType
	}
	return ""
}

func (x *QualifiedEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *QualifiedEvent) GetRiskScore() uint32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *QualifiedEvent) GetIngestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestedAt
	}
	return nil
}

func (x *QualifiedEvent) GetRawPayloadJson() string {
	if x != nil {
		return x.RawPayloadJson
	}
	return ""
}

func (x *QualifiedEvent) GetProvenanceGraph() string {
	if x != nil {
		return x.ProvenanceGraph
	}
	return ""
}

var File_soc_service_proto protoreflect.FileDescriptor

const file_soc_service_proto_rawDesc = "" +
	"\n" +
	"\x11soc_service.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x11LogContextRequest\x12!\n" +
	"\fevidence_ids\x18\x01 \x03(\tR\vevidenceIds\x12*\n" +
	"\x11max_records_limit\x18\x02 \x01(\x05R\x0fmaxRecordsLimit\"\xb9\x04\n" +
	"\x13SecurityEventDetail\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12%\n" +
	"\x0eprincipal_user\x18\x04 \x01(\tR\rprincipalUser\x12'\n" +
	"\x0faction_executed\x18\x05 \x01(\tR\x0eactionExecuted\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x06 \x01(\rR\triskScore\x12%\n" +
	"\x0edestination_ip\x18\a \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\b \x01(\x05R\x0fdestinationPort\x12\x1a\n" +
	"\bprotocol\x18\t \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"dns_domain\x18\n" +
	" \x01(\tR\tdnsDomain\x12\x17\n" +
	"\aflow_id\x18\v \x01(\tR\x06flowId\x12\x1b\n" +
	"\tbytes_out\x18\f \x01(\x04R\bbytesOut\x12\x19\n" +
	"\bbytes_in\x18\r \x01(\x04R\abytesIn\x12\x1f\n" +
	"\vpackets_out\x18\x0e \x01(\rR\n" +
	"packetsOut\x12\x1d\n" +
	"\n" +
	"packets_in\x18\x0f \x01(\rR\tpacketsIn\x12#\n" +
	"\rflow_duration\x18\x10 \x01(\x01R\fflowDuration\"\x8d\x01\n" +
	"\x12LogContextResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12.\n" +
	"\x13current_batch_index\x18\x02 \x01(\x05R\x11currentBatchIndex\x12/\n" +
	"\x06events\x18\x03 \x03(\v2\x17.pb.SecurityEventDetailR\x06events\"\xc3\x01\n" +
	"\x15BlockDirectiveRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12$\n" +
	"\rjustification\x18\x02 \x01(\tR\rjustification\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12+\n" +
	"\x11authorization_jwt\x18\x05 \x01(\tR\x10authorizationJwt\"\x86\x01\n" +
	"\x16BlockDirectiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\tR\x05logId\x12;\n" +
	"\vexecuted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\":\n" +
	"\x13SubscriptionRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\"\xea\x02\n" +
	"\x0eQualifiedEvent\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rendpoint_type\x18\x04 \x01(\tR\fendpointType\x12\x1b\n" +
	"\tsource_ip\x18\x05 \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x06 \x01(\rR\triskScore\x12;\n" +
	"\vingested_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestedAt\x12(\n" +
	"\x10raw_payload_json\x18\b \x01(\tR\x0erawPayloadJson\x12)\n" +
	"\x10provenance_graph\x18\t \x01(\tR\x0fprovenanceGraph2\xf6\x01\n" +
	"\x14IngestionCoreService\x12D\n" +
	"\x11FetchAlertContext\x12\x15.pb.LogContextRequest\x1a\x16.pb.LogContextResponse0\x01\x12K\n" +
	"\x12PushBlockDirective\x12\x19.pb.BlockDirectiveRequest\x1a\x1a.pb.BlockDirectiveResponse\x12K\n" +
	"\x1aSubscribeToQualifiedEvents\x12\x17.pb.SubscriptionRequest\x1a\x12.pb.QualifiedEvent0\x01B\x10Z\x0ecore-ingest/pbb\x06proto3"

var (
	file_soc_service_proto_rawDescOnce sync.Once
	file_soc_service_proto_rawDescData []byte
)

func file_soc_service_proto_rawDescGZIP() []byte {
	file_soc_service_proto_rawDescOnce.Do(func() {
		file_soc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_soc_service_proto_rawDesc), len(file_soc_service_proto_rawDesc)))
	})
	return file_soc_service_proto_rawDescData
}

var file_soc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_soc_service_proto_goTypes = []any{
	(*LogContextRequest)(nil),      // 0: pb.LogContextRequest
	(*SecurityEventDetail)(nil),    // 1: pb.SecurityEventDetail
	(*LogContextResponse)(nil),     // 2: pb.LogContextResponse
	(*BlockDirectiveRequest)(nil),  // 3: pb.BlockDirectiveRequest
	(*BlockDirectiveResponse)(nil), // 4: pb.BlockDirectiveResponse
	(*SubscriptionRequest)(nil),    // 5: pb.SubscriptionRequest
	(*QualifiedEvent)(nil),         // 6: pb.QualifiedEvent
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_soc_service_proto_depIdxs = []int32{
	7, // 0: pb.SecurityEventDetail.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: pb.LogContextResponse.events:type_name -> pb.SecurityEventDetail
	7, // 2: pb.BlockDirectiveResponse.executed_at:type_name -> google.protobuf.Timestamp
	7, // 3: pb.QualifiedEvent.ingested_at:type_name -> google.protobuf.Timestamp
	0, // 4: pb.IngestionCoreService.FetchAlertContext:input_type -> pb.LogContextRequest
	3, // 5: pb.IngestionCoreService.PushBlockDirective:input_type -> pb.BlockDirectiveRequest
	5, // 6: pb.IngestionCoreService.SubscribeToQualifiedEvents:input_type -> pb.SubscriptionRequest
	2, // 7: pb.IngestionCoreService.FetchAlertContext:output_type -> pb.LogContextResponse
	4, // 8: pb.IngestionCoreService.PushBlockDirective:output_type -> pb.BlockDirectiveResponse
	6, // 9: pb.IngestionCoreService.SubscribeToQualifiedEvents:output_type -> pb.QualifiedEvent
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_soc_service_proto_init() }
func file_soc_service_proto_init() {
	if File_soc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_soc_service_proto_rawDesc), len(file_soc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soc_service_proto_goTypes,
		DependencyIndexes: file_soc_service_proto_depIdxs,
		MessageInfos:      file_soc_service_proto_msgTypes,
	}.Build()
	File_soc_service_proto = out.File
	file_soc_service_proto_goTypes = nil
	file_soc_service_proto_depIdxs = nil
}
