# MASTER ORCHESTRATION MAKEFILE FOR HYBRID SIEM/SOAR PLATFORM

.PHONY: all proto-go proto-python build-go run-stack clean certbot-renew

all: proto-go proto-python build-go run-stack

proto-go:
	@echo "🛠️ Compiling Go Protobuf schemas..."
	protoc --proto_path=shared-proto \
		--go_out=core-ingest/pb --go_opt=paths=source_relative \
		--go-grpc_out=core-ingest/pb --go-grpc_opt=paths=source_relative \
		shared-proto/soc_service.proto

proto-python:
	@echo "🛠️ Compiling Python Protobuf schemas..."
	python -m grpc_tools.protoc --proto_path=shared-proto \
		--python_out=soc-backend/pb \
		--grpc_python_out=soc-backend/pb \
		shared-proto/soc_service.proto
	@echo "📦 Fixing relative pathing imports inside autogenerated files..."
	python -c " \
	path = 'soc-backend/pb/soc_service_pb2_grpc.py'; \
	data = open(path).read(); \
	data = data.replace('import soc_service_pb2 as soc_service__pb2', 'from . import soc_service_pb2 as soc_service__pb2'); \
	open(path, 'w').write(data);"

build-go:
	@echo "🏗️ Compiling static architecture binary for Go Core Ingest..."
	cd core-ingest && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o soc_ingest_core .

run-stack:
	# ==============================================================================
	# 1. 🌐 COMPONENT PLACEMENT & GLOBAL WORKFLOW TRACE
	#    - Master Boot Orchestrator: Local environment entry point.
	#    - Upstream: Developer Console | Downstream: Docker Daemon / Init Script
	# 🛡️ 2. LOGICAL INTENT & SYSTEM RESPONSIBILITY
	#    - Initiates the `docker-compose` topology and explicitly triggers the ephemeral
	#      Release Phase bootstrapper script to validate schemas.
	# 🚨 3. CLOUD GUARDRAILS & DESKTOP-TO-PROD PARITY CONSTRAINTS
	#    - Replicates Cloud PaaS Pre-Deploy hooks by running `init-platform.sh` safely
	#      after the network bridge is established, keeping local execution identical to cloud.
	# 🔗 4. CROSS-MODULE INTERFACE & SCHEMA CONTRACTS
	#    - Interacts with `docker-compose.yml` and `init-platform.sh`.
	# ☣️ 5. CASCADING FAILURE MODE & RESILIENCE STATE
	#    - Failure Mode: Containers crash during boot or schema injection fails.
	#    - Fallback State: Fails synchronously in the terminal, aborting the `make` execution.
	# ==============================================================================
	@echo "🚀 Orchestrating Zero-Trust Docker Container Network..."
	cd deploy && docker compose up --build -d
	@echo "⏳ Waiting for containers to initialize..."
	@sleep 5
	@echo "⚡ Executing Local Bootstrapper (Simulating PaaS Pre-Deploy)..."
	cd deploy && bash init-platform.sh

# FIXED: Service-aware execution mapping with headless terminal bypass (-T)
certbot-renew:
	@echo "🔐 Renewing Let's Encrypt TLS Certificates..."
	MSYS_NO_PATHCONV=1 docker run --rm --name certbot \
	    -v "/etc/letsencrypt:/etc/letsencrypt" \
	    -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
	    -v "/usr/share/nginx/html:/var/www/certbot" \
	    certbot/certbot renew --webroot -w /var/www/certbot --quiet
	@echo "🔄 Reloading Nginx service configurations gracefully..."
	cd deploy && docker compose exec -T soc-frontend nginx -s reload

clean:
	@echo "🧹 Purging environment builds..."
	rm -f core-ingest/soc_ingest_core
	rm -rf core-ingest/pb/*
	rm -rf soc-backend/pb/*
