#!/usr/bin/env bash
# ───────────────────────────────────────────────────────────────
# CROSS-PLATFORM DEVELOPMENT ORCHESTRATOR FOR WINDOWS MINGW64
# Falls back to native shell execution if GNU 'make' is missing.
# ───────────────────────────────────────────────────────────────
set -euo pipefail

# Force MINGW64 to stop altering absolute POSIX path flags during Docker mappings
export MSYS_NO_PATHCONV=1

# Ensure Go binaries are in the PATH for protoc-gen-go plugins (Windows Git Bash path conversion)
GOPATH_BIN=$(cygpath -u "$(go env GOPATH)")/bin
export PATH="$PATH:$GOPATH_BIN"

echo "🧹 [1/5] Purging old build footprints..."
rm -f core-ingest/soc_ingest_core
mkdir -p core-ingest/pb soc-backend/pb
rm -rf core-ingest/pb/*
rm -rf soc-backend/pb/*

echo "🛠️ [2/5] Compiling Go Protobuf schemas..."
./protoc.exe --proto_path=shared-proto --proto_path=include \
	--go_out=core-ingest/pb --go_opt=paths=source_relative \
	--go-grpc_out=core-ingest/pb --go-grpc_opt=paths=source_relative \
	shared-proto/soc_service.proto

echo "🛠️ [3/5] Compiling Python Protobuf schemas..."
python -m grpc_tools.protoc --proto_path=shared-proto \
	--python_out=soc-backend/pb \
	--grpc_python_out=soc-backend/pb \
	shared-proto/soc_service.proto

echo "📦 [4/5] Fixing relative pathing imports inside autogenerated files..."
python -c "path = 'soc-backend/pb/soc_service_pb2_grpc.py'; data = open(path).read(); data = data.replace('import soc_service_pb2 as soc_service__pb2', 'from . import soc_service_pb2 as soc_service__pb2'); open(path, 'w').write(data);"

echo "🏗️ [5/5] Compiling static architecture binary for Go Core Ingest..."
cd core-ingest
go mod tidy
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o soc_ingest_core .
cd ..

echo "🚀 Orchestrating Zero-Trust Docker Container Network..."
cd deploy
docker compose up --build -d

echo "✅ Hybrid SIEM/SOAR Ecosystem successfully initialized!"
