# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import soc_service_pb2 as soc__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in soc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionCoreServiceStub:
    """The Ingestion Core Service manages type-safe data pipelines between Go and Python Agent layers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchAlertContext = channel.unary_stream(
                '/pb.IngestionCoreService/FetchAlertContext',
                request_serializer=soc__service__pb2.LogContextRequest.SerializeToString,
                response_deserializer=soc__service__pb2.LogContextResponse.FromString,
                _registered_method=True)
        self.PushBlockDirective = channel.unary_unary(
                '/pb.IngestionCoreService/PushBlockDirective',
                request_serializer=soc__service__pb2.BlockDirectiveRequest.SerializeToString,
                response_deserializer=soc__service__pb2.BlockDirectiveResponse.FromString,
                _registered_method=True)


class IngestionCoreServiceServicer:
    """The Ingestion Core Service manages type-safe data pipelines between Go and Python Agent layers.
    """

    def FetchAlertContext(self, request, context):
        """FETCH LOG CONTEXT (FIXED: Uses Server-to-Client Streaming to handle massive logs without RAM bloat)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushBlockDirective(self, request, context):
        """CONTAINMENT CALLS (FIXED: Asynchronous, audited, and strictly validated)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionCoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchAlertContext': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchAlertContext,
                    request_deserializer=soc__service__pb2.LogContextRequest.FromString,
                    response_serializer=soc__service__pb2.LogContextResponse.SerializeToString,
            ),
            'PushBlockDirective': grpc.unary_unary_rpc_method_handler(
                    servicer.PushBlockDirective,
                    request_deserializer=soc__service__pb2.BlockDirectiveRequest.FromString,
                    response_serializer=soc__service__pb2.BlockDirectiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.IngestionCoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.IngestionCoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionCoreService:
    """The Ingestion Core Service manages type-safe data pipelines between Go and Python Agent layers.
    """

    @staticmethod
    def FetchAlertContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pb.IngestionCoreService/FetchAlertContext',
            soc__service__pb2.LogContextRequest.SerializeToString,
            soc__service__pb2.LogContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushBlockDirective(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.IngestionCoreService/PushBlockDirective',
            soc__service__pb2.BlockDirectiveRequest.SerializeToString,
            soc__service__pb2.BlockDirectiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
