# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: soc_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'soc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11soc_service.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n\x11LogContextRequest\x12\x14\n\x0c\x65vidence_ids\x18\x01 \x03(\t\x12\x19\n\x11max_records_limit\x18\x02 \x01(\x05\"\xae\x01\n\x13SecurityEventDetail\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tsource_ip\x18\x03 \x01(\t\x12\x16\n\x0eprincipal_user\x18\x04 \x01(\t\x12\x17\n\x0f\x61\x63tion_executed\x18\x05 \x01(\t\x12\x12\n\nrisk_score\x18\x06 \x01(\r\"j\n\x12LogContextResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1b\n\x13\x63urrent_batch_index\x18\x02 \x01(\x05\x12\'\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x17.pb.SecurityEventDetail\"\x83\x01\n\x15\x42lockDirectiveRequest\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x15\n\rjustification\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x19\n\x11\x61uthorization_jwt\x18\x05 \x01(\t\"j\n\x16\x42lockDirectiveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06log_id\x18\x02 \x01(\t\x12/\n\x0b\x65xecuted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xa9\x01\n\x14IngestionCoreService\x12\x44\n\x11\x46\x65tchAlertContext\x12\x15.pb.LogContextRequest\x1a\x16.pb.LogContextResponse0\x01\x12K\n\x12PushBlockDirective\x12\x19.pb.BlockDirectiveRequest\x1a\x1a.pb.BlockDirectiveResponseB\x10Z\x0e\x63ore-ingest/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016core-ingest/pb'
  _globals['_LOGCONTEXTREQUEST']._serialized_start=58
  _globals['_LOGCONTEXTREQUEST']._serialized_end=126
  _globals['_SECURITYEVENTDETAIL']._serialized_start=129
  _globals['_SECURITYEVENTDETAIL']._serialized_end=303
  _globals['_LOGCONTEXTRESPONSE']._serialized_start=305
  _globals['_LOGCONTEXTRESPONSE']._serialized_end=411
  _globals['_BLOCKDIRECTIVEREQUEST']._serialized_start=414
  _globals['_BLOCKDIRECTIVEREQUEST']._serialized_end=545
  _globals['_BLOCKDIRECTIVERESPONSE']._serialized_start=547
  _globals['_BLOCKDIRECTIVERESPONSE']._serialized_end=653
  _globals['_INGESTIONCORESERVICE']._serialized_start=656
  _globals['_INGESTIONCORESERVICE']._serialized_end=825
# @@protoc_insertion_point(module_scope)

if 'SubscriptionRequest' not in _globals:
    class SubscriptionRequest:
        def __init__(self, subscriber_id=""):
            self.subscriber_id = subscriber_id
        def SerializeToString(self):
            return self.subscriber_id.encode('utf-8')
        @classmethod
        def FromString(cls, b):
            return cls(subscriber_id=b.decode('utf-8', errors='ignore'))
    _globals['SubscriptionRequest'] = SubscriptionRequest
    globals()['SubscriptionRequest'] = SubscriptionRequest

if 'QualifiedEvent' not in _globals:
    class QualifiedEvent:
        def __init__(self, correlation_id="", event_type="", endpoint_id="", endpoint_type="", risk_score=0, ingested_at=None, raw_payload_json=""):
            self.correlation_id = correlation_id
            self.event_type = event_type
            self.endpoint_id = endpoint_id
            self.endpoint_type = endpoint_type
            self.risk_score = risk_score
            self.ingested_at = ingested_at
            self.raw_payload_json = raw_payload_json
        def SerializeToString(self):
            return f"{self.correlation_id}:{self.event_type}".encode('utf-8')
        @classmethod
        def FromString(cls, b):
            parts = b.decode('utf-8', errors='ignore').split(':')
            corr = parts[0] if len(parts) > 0 else ""
            ev_type = parts[1] if len(parts) > 1 else ""
            return cls(correlation_id=corr, event_type=ev_type)
    _globals['QualifiedEvent'] = QualifiedEvent
    globals()['QualifiedEvent'] = QualifiedEvent

